<?php
$title = "Chamado";
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1>
        <?php
        echo $this->escapeHtml($title);
        ?>
        <small>
            status: <font style="color:<?php
            if ($chamado->chamado_status == 'aberto') {
                echo '#996600';
            } elseif ($chamado->chamado_status == 'em andamento') {
                echo '#000066';
            } elseif ($chamado->chamado_status == 'pausado') {
                echo '#996600';
            } elseif ($chamado->chamado_status == 'fechado') {
                echo '#006600';
            } elseif ($chamado->chamado_status == 'cancelado') {
                echo '#660000';
            }
            ?>">
                          <?php
                          echo $this->escapeHtml($chamado->chamado_status);
                          ?>
            </font>
        </small>
    </h1>
    <br>
    <div>
       
        <strong>
            Usuário:
        </strong>
        <a href="<?php echo $this->escapeHtml($this->url('usuario/exibirusuario') . '/' . $chamado->usuario_id) ?>" style="color:black">
            <?php
            echo $this->escapeHtml($usuario);
            ?>
        </a>
        <br>
        <strong>
            Técnico:
        </strong>
        <?php
        if ($tecnico == 'Sem Técnico') {
            echo $this->escapeHtml('Sem Ténico Responsável');
        } else {
            ?>
            <a href="<?php echo $this->escapeHtml($this->url('usuario/exibirusuario') . '/' . $chamado->usuario_id_tecnico) ?>" style="color:black">
                <?php
                echo $this->escapeHtml($tecnico);
                ?>
            </a>
            <?php
        }
        ?>
        <br>
        <strong>
            Categoria do Chamado:
        </strong>
        <?php
        echo $this->escapeHtml($cat_chamado);
        echo ' ';
        echo $this->escapeHtml($sub_cat_chamado);
        ?>
        <br>
        <strong>
            Equipamento: 
        </strong>
        <a href="<?php echo $this->escapeHtml($this->url('gerenciar/exibirequipamento') . '/' . $chamado->equipamento_id) ?>" style="color: black;">
            <?php
            echo $this->escapeHtml($cat_equipamento);
            ?>
            <?php
            echo $this->escapeHtml($sub_cat_equipamento);
            ?>
            <?php
            echo $this->escapeHtml($equipamento);
            ?>
        </a>
        <br>
        <br>
        <a class="btn btn-warning" href="<?php echo $this->escapeHtml($this->url('chamado/editchamado') . '/' . $chamado->id) ?>">
            Editar
        </a>
        &nbsp;&nbsp;
        <a class="btn btn-success" href="<?php echo $this->escapeHtml($this->url('chamado')) ?>">
            Voltar
        </a>
        <br>
        <br>
    </div>
          
        <table class='table table-hover' style='font-size: medium;'>
            <tr>
                <th colspan='5'>
                   Histórico 
                </th>
            </tr>
                <th>
                    Ação  
                </th>
                <th>
                    Descrição
                </th>
                <th>
                    Data e Hora
                </th>
                <th>
                    Usuário
                </th>
                <th>
                    Perfil
                </th>
            </tr>
            <?php
            foreach ($historicos as $historico):
                ?>
                <tr>
                    <td>
                        <?php
                        echo $this->escapeHtml($historico->acao);
                        ?>
                    </td>
                    <td>
                        <?php
                        echo $this->escapeHtml($historico->descricao);
                        ?>
                    </td>                    
                    <td>
                        <?php
                        $dataehora = $historico->datahora;
                        list($data, $hora)= explode(" ", $dataehora);
                        list ($ano, $mes, $dia) = explode('-',$data);                       
                        $dataf = $dia."/".$mes."/".$ano;
                        echo $this->escapeHtml($dataf." às ".$hora);
                        ?>
                    </td>                    
                    <td>
                        <?php
                         echo $this->escapeHtml($hist_users[$historico->id]);
                        ?>
                    </td>
                    <td>
                        <?php
                         echo $this->escapeHtml($hist_perfil[$historico->id]);
                        ?>
                    </td>
                </tr>
                <?php
            endforeach;
            ?>
        </table>
    </div> 

