
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            PAGINA<br>
            * pesquisar<br>
            ----------<br>
            FUNÇÃO<br>
            *listar e filtrar chamados <br>
            ----------<br>
            ATORES<br>
            *tec, ger<br>
            ----------<br>
            CONTROLE DE ACESSO OU DETALHES<br>
            *usuário só tem acesso aos seus prórpios chamados. <br>
            <br>
            <?php
            
            $chamado = $this->chamado;
            
            var_dump($chamado);
                    
            
            ?>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
 
