<?php
$title = "Listagem de Chamados";
$this->headTitle($title);

$id_user = 2;
?>
<h1>
            <?php echo $this->escapeHtml($title); ?>
        </h1>
<br>
<br>
<table class="table table-hover">
    <tr>
        <th>Status</th>
        <th>Usuário</th>        
        <th>Categoria</th>
        <th>Subcategoria</th>
        <th>Equipamento</th>
        <th>Técnico Responsável</th>
        <th>
            <a class="btn-sm btn-info" href="<?php echo $this->escapeHtml($this->url('chamado/addchamado') . '/' . $id_user) ?>">
                Adicionar Chamado
            </a>
        </th>
    </tr>
    <?php foreach ($chamados as $chamado) : ?>
        <tr>           
            <td><?php echo $this->escapeHtml($chamado->chamado_status); ?></td>
            <td><?php echo $this->escapeHtml($usuarios[$chamado->usuario_id]); ?></td>            
            <td> <?php echo $this->escapeHtml($categoriachamados[$chamado->chamado_subcategoria_id]); ?></td>
            <td><?php echo $this->escapeHtml($subcategoriachamados[$chamado->chamado_subcategoria_id]); ?></td>
            <td><?php echo $this->escapeHtml($equipamentos[$chamado->equipamento_id]); ?></td>
            <td><?php echo $this->escapeHtml($tecnicos[$chamado->usuario_id_tecnico]); ?></td>            
            <td>
                <a href="<?php echo $this->escapeHtml($this->url('chamado/exibirchamado') . '/' . $chamado->id); ?>" class="btn-sm btn-warning">                                       
                    Exibir Chamado
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
