<?php
$title = 'Adicionar Empresa';
$this->headTitle($title);
?>

<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>
<br>&nbsp;
<br>

<?php

?>
<form class="form" method="POST" action="<?php echo $this->escapeHtml($this->url('gerenciar/addempresas')) ?>">
    <div class="form-group">
        <label for="nome">Nome:
        </label>
        <input id="nome" name="nome" type="text" class="form-control"> 
    </div>
    <div class="form-group">
        <label for="usuario_id_responsavel">Responsável:
        </label>
        <select id="modalidade" name="usuario_id_responsavel" class="form-control">
            <option value="1">A adicionar</option>
            
        </select>
    </div>
    <input type="submit" value="Salvar" class="btn btn-success">

    &nbsp;&nbsp;&nbsp;
    <button class="btn btn-warning">
        <a href="<?php echo $this->escapeHtml($this->url('gerenciar/listarempresas')); ?>" style="color: white" >
            Voltar       
        </a>
    </button>
</form>
<br>
<br>