<?php
$title = 'Excluir Empresa';
$this->headTitle($title);
?>

 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     <?php  echo $this->escapeHtml($empresa->nome); ?>' by
    
 </p>
 <?php
 $url = $this->escapeHtml($this->url('gerenciar/delempresas') . '?id=' . $empresa->id);
 

 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $empresa->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>