<?php
$title = 'Editar Empresa';
$this->headTitle($title);
?>

    <h1>
        <?php echo $this->escapeHtml($title); ?>
    </h1>
<br>&nbsp;
    <br>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('gerenciar/editempresas'));
$form->prepare();
echo "<div class='form-group'>";
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo "&nbsp;&nbsp;";
echo $this->formRow($form->get('usuario_id_responsavel'));
echo "</div>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
    &nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->escapeHtml($this->url('gerenciar/empresas')) ?>" >
    <button class="btn btn-sm btn-warning" onclick="">
    Voltar
    </button>
</a>
    
    <br>
    <br>