<?php
$title = 'Editar Empresa';
$this->headTitle($title);
?>

<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>
<br>&nbsp;
<br>


<?php
$empresa = $this->empresa;
$funcionarios = $this->funcionarios;
$responsavel = $this->responsavel;
?>

<form class="form" method="POST" action="<?php echo $this->escapeHtml($this->url('gerenciar/editempresasave') . '/' . $empresa->id) ?>">
    <div class="form-group">
        <label for="nome">Nome:
        </label>
        <input id="nome" name="nome" type="text" class="form-control" value="<?php echo $this->escapeHtml($empresa->nome); ?>"> 
    </div>
    <input type="hidden" value="<?php echo $this->escapeHtml($empresa->id); ?>">
    <div class="form-group">
        <label for="usuario_id_responsavel">Responsável:
        </label>
        <select id="modalidade" name="usuario_id_responsavel" class="form-control">
            <option value="<?php echo $this->escapeHtml($empresa->usuario_id_responsavel); ?>"><?php echo $this->escapeHtml($responsavel); ?> (selecionado) </option>
            <?php foreach ($funcionarios as $funcionario) : ?>
                <option value="<?php echo $this->escapeHtml($funcionario->id); ?>">
                    <?php echo $this->escapeHtml($funcionario->nome); ?>  
                </option>       
            <?php endforeach; ?>
        </select>
    </div>
    <input type="submit" value="Salvar" class="btn btn-success">

    &nbsp;&nbsp;&nbsp;
    <button class="btn btn-warning">
        <a href="<?php echo $this->escapeHtml($this->url('gerenciar/empresas')); ?>" style="color: white" >
            Voltar       
        </a>
    </button>
</form>
<br>
<br>