<?php
$title = "Gerenciamento de Empresas";
$this->headTitle($title);
?>
<br>
<?php
if (isset($_GET["msg"])) {
    $msg = $_GET["msg"];

    if ($msg = 'empresanotfind') {

        echo '<div class="alert alert-warning alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Erro!</strong> Empresa não encontrada!.
</div>';
    }
}
?>
<script>

    $(function() {
        $('.checkbox-divida').change(function() {
            var idDivida = $(this).prop('id');
            var tipoDivida = $(this).prop('name');
            var parentTR = $(this).parents('tr');
            $.ajax('<?php  echo $this->url('usuario/nomefuncionario'); ?>', {
                data: {id: idDivida, tipo: tipoDivida},
                type: 'GET',
                success: function(data) {
                    if (data === '{"estado":1}') {
                        parentTR.attr("class", "danger");
                    }
                    if (data === '{"estado":0}') {
                        parentTR.attr("class", " ");
                    }
                },
                error: function(error) {
                    alert(error);
                }
            });
        });
    });
</script>
<br>
<div class="row">
    <div class="col-lg-8">
        <h1>
<?php echo $this->escapeHtml($title); ?>        
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-3" style="position:absolute;
         right:0px;">
        <a href="<?php echo $this->escapeHtml($this->url('gerenciar/addempresas')) ?>" class="btn-sm btn-primary">
            Adicionar Empresas
        </a>
    </div>
</div>
<br>
<br>


<div class="table-responsive">
    <table class="table table-hover table-striped table-responsive" style="text-align: center">
        <tr class="success">          
            <th style="text-align: center">Nome da Empresa</th>
            <th  style="text-align: center">Gerente Responsável</th>
            <th style="text-align: center">&nbsp;</th>
            <th style="text-align: center">&nbsp;</th> 
        </tr>

<?php foreach ($empresas as $empresa) : ?>
            <tr>                
                <td>
    <?php echo $this->escapeHtml($empresa->nome); ?>
                </td>
                <td>
    <?php echo $this->escapeHtml($empresa->usuario_id_responsavel); ?>
                </td>
                <td>
                    <a href="<?php echo $this->escapeHtml($this->url('gerenciar/editempresas') . '/' . $empresa->id); ?>" class="btn-sm btn-warning">                                       
                        Editar empresa
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->escapeHtml($this->url('gerenciar/delempresas') . '?id=' . $empresa->id); ?>" class="btn-sm btn-danger">  
                        Excluir empresa
                    </a>
                </td>          
            </tr>           

<?php endforeach; ?>
    </table>
</div>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
