
<br>
<div class="row">
    <div class="col-lg-6">
        <div class=" divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
             <br>
            PAGINA<br>
            * historico equipamentos<br>
            ----------<br>
            FUNÇÃO<br>
            *visualização do histórico<br>
            ----------<br>
            ATORES<br>
            *tec, ger<br>
            ----------<br>
            CONTROLE DE ACESSO OU DETALHES<br>
            *tecnico e gerente visualizam dados referentes a todos os equipamentos
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>              
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">        
        <div class="divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
</div>
