
<br>
<div class="row">
    <div class="col-lg-6">
        <div class=" divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
             <br>
            PAGINA<br>
            * usuarios<br>
            ----------<br>
            FUNÇÃO<br>
            *cadastro de usuários<br>
            *listar e filtrar usuários do sistema<br>
            ----------<br>
            ATORES<br>
            *tec, ger<br>
            ----------<br>
            CONTROLE DE ACESSO OU DETALHES<br>
            *deve existir um usuário default para cadastro do gerente, <br>
             técnico apenas poderá cadastrar usuários<br>
            *técnico visualiza usuários. gerente visualiza técncos e usuários
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>              
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">        
        <div class="divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
</div>
