
<br>
<div class="row">
    <div class="col-lg-6">
        <div class=" divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
             <br>
            TESTEEEEEEE
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>              
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">        
        <div class="divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
</div>
