<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="margin: 0px">
            <div class="navbar-inner" style="margin-left: 5px; margin-right: 20px">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('index') ?>"><img style="width: 25px;height: 25px" src="<?php echo $this->basePath('img/sigc-logo.png') ?>" alt="SiGC"/>
                        &nbsp;&nbsp;SiGC&nbsp;&nbsp;
                    </a>

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>
                                    <span class="glyphicon glyphicon-list-alt"></span>
                                    &nbsp;Chamados
                                </b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->url('chamado/criarchamados') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-plus-sign"></span>
                                            &nbsp;  Criar
                                        </b>
                                    </a>
                                </li> 
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('chamado/formulariochamados') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-close"></span>
                                            &nbsp;   Meus Chamados
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('chamado/historicochamados') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-open"></span>
                                            &nbsp;    Em aberto
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('chamado/listarchamados') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-search"></span>
                                            &nbsp;   Pesquisar
                                        </b>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                     <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>
                                    <span class="glyphicon glyphicon-wrench"></span>
                                    &nbsp;Gerenciar
                                </b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->url('gerenciar/listarusuarios') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-user"></span>
                                            &nbsp;  Usuários
                                        </b>
                                    </a>
                                </li> 
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('gerenciar/formularioequipamentos') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-hdd"></span>
                                            &nbsp;   Equipamentos
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('gerenciar/formulariotipoequipamento') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-print"></span>
                                            &nbsp;    Categorias de Equipamentos
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('gerenciar/formulariocategorias') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-close"></span>
                                            &nbsp;   Categorias de Chamado
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('gerenciar/historicoequipamento') ?>">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-close"></span>
                                            &nbsp;   Historico Equipamentos
                                        </b>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                        <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="<?php echo $this->url('painel/painelcontrole') ?>">
                                <b>
                                    <span class="glyphicon glyphicon-wrench"></span>
                                    &nbsp;Painel de Controle
                                </b>
                            </a>                             
                        </li>
                    </ul>
             
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>
                                    <span class="glyphicon glyphicon-lock"></span> 
                                    'Usuario Logado'
                                </b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>   
                                    <a href="<?php echo $this->url('usuario/perfil') ?>">                                
                                     
                                        <b>
                                            <span class="glyphicon glyphicon-user"></span>                            
                                            &nbsp; Perfil
                                        </b>
                                    </a>                                  
                                </li> 
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <b>
                                            <span class="glyphicon glyphicon-log-out"></span>
                                            &nbsp; Deslogar
                                        </b>
                                    </a>
                                </li>                
                            </ul>
                        </li>
                    </ul>                    
                </div>
            </div>
            <div class="row" style="margin: 0px; padding: opx;">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding: 0;">
                    <hr style="border-top-color: #03899c; margin: 0px; border-top-width: 3px;" width="100%">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding: 0;">
                    <hr style="border-top-color: #162eae; margin: 0px; border-top-width: 3px;">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding: 0;">
                    <hr style="border-top-color: #14d100; margin: 0px; border-top-width: 3px;">
                </div>
            </div>
        </nav>
        <br>
       
        <div class="container divCard">
            <?php echo $this->content; ?>
            <br>
            
            <div class="row" style="margin: 0px; padding: opx;">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding: 0;">
                    <hr style="border-top-color: #03899c; margin: 0px; border-top-width: 2px;" width="100%">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding: 0;">
                    <hr style="border-top-color: #162eae; margin: 0px; border-top-width: 2px;">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding: 0;">
                    <hr style="border-top-color: #14d100; margin: 0px; border-top-width: 2px;">
                </div>
            </div>
          <footer>
                <p>Trabalho de Projeto Aplicado 5º Semestre 2014/1 Grupo 4 (ou 5) UNA</p>
            </footer>
        </div> <!-- /container -->
     
    </body>
</html>
