<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img style="width: 25px;height: 25px" src="<?php echo $this->basePath('img/sigc-logo.png') ?>" alt="SiGC"/>
                        &nbsp;&nbsp;SiGC&nbsp;&nbsp;
                    </a>

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>
                                    <span class="glyphicon glyphicon-list-alt"></span>
                                    &nbsp;Chamados
                                </b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-plus-sign"></span>
                                            &nbsp;  Criar
                                        </b>
                                    </a>
                                </li> 
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-close"></span>
                                            &nbsp;   Meus Chamados
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-open"></span>
                                            &nbsp;    Em aberto
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-search"></span>
                                            &nbsp;   Pesquisar
                                        </b>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                     <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>
                                    <span class="glyphicon glyphicon-wrench"></span>
                                    &nbsp;Gerenciar
                                </b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-user"></span>
                                            &nbsp;  Usuários
                                        </b>
                                    </a>
                                </li> 
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-hdd"></span>
                                            &nbsp;   Equipamentos
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-print"></span>
                                            &nbsp;    Categorias de Equipamentos
                                        </b>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <b>
                                            <span class="glyphicon glyphicon-folder-close"></span>
                                            &nbsp;   Categorias de Chamado
                                        </b>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                        <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="<?php echo $this->url('gerenciar/painel') ?>" class="dropdown-toggle" data-toggle="dropdown">
                                <b>
                                    <span class="glyphicon glyphicon-wrench"></span>
                                    &nbsp;Painel de Controle
                                </b>
                            </a>                             
                        </li>
                    </ul>
             
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>                                    
                                    <a href="#">
                                        <b>
                                            <span class="glyphicon glyphicon-user"></span>                            
                                            &nbsp; Minha Conta
                                        </b>
                                    </a>                                  
                                </li> 
                                <li class="divider"></li>
                                <li>

                                    <a href="#">
                                        <b>
                                            <span class="glyphicon glyphicon-log-out"></span>
                                            &nbsp; Deslogar
                                        </b>
                                    </a>

                                </li>                
                            </ul>
                        </li>                              

                    </ul>                    
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p></p>
            </footer>
        </div> <!-- /container -->
     
    </body>
</html>
