
<br>
<div class="row">
    <div class="col-lg-6">
        <div class=" divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
             <br>
            PAGINA<br>
            * em aberto<br>
            ----------<br>
            FUNÇÃO<br>
            *visualização do histórico de um chamados abertos<br>
            ----------<br>
            ATORES<br>
            *tec, ger, user<br>
            ----------<br>
            CONTROLE DE ACESSO OU DETALHES<br>
            *usuário só vê seus chamados, técnico e gerente vem todos.
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>              
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="divCard">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">        
        <div class="divCard">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="divCard">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
</div>
