<?php
$title = "Listagem de Usuários";
$this->headTitle($title);

?>
<h1>
            <?php echo $this->escapeHtml($title); ?>
        </h1>
<br>
<br>
<table class="table table-hover">
    <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Perfil</th>
        <th>Setor</th>
        <th>
            <a class="btn-sm btn-info" href="<?php echo $this->escapeHtml($this->url('usuario/addusuario')) ?>">
                Adicionar Usuário
            </a>
        </th>
    </tr>
    <?php foreach ($usuarios as $usuario) : ?>
        <tr>           
            <td><?php echo $this->escapeHtml($usuario->nome); ?></td>
            <td><?php echo $this->escapeHtml($usuario->email); ?></td>            
            <td> <?php echo $this->escapeHtml($usuario->telefone); ?></td>
            <td><?php echo $this->escapeHtml($usuario->perfil); ?></td>
            <td><?php echo $this->escapeHtml($setores[$usuario->id]); ?></td>
            <td>
                <a href="<?php echo $this->escapeHtml($this->url('usuario/editusuario') . '/' . $usuario->id); ?>" class="btn-sm btn-warning">                                       
                    Editar Usuário
                </a>
            </td>
        </tr>
        <?php
       
        
    endforeach; 
   
    ?>
</table>
<br>
