



<div class="row">

    <div class="jumbotron">
        <h1>S<font style="color: limegreen"    >i</font>GC</h1>

        <p>Sistema de Gerenciamento de Chamados!!!</p>
    </div>


</div>
<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2">
        <div class="list-group">
            <a href="#" class="list-group-item active">
                Menu Rápido
            </a>
            <a href="#" class="list-group-item">Criar novo chamado</a>
            <a href="#" class="list-group-item">Ver seus chamados</a>
            <a href="#" class="list-group-item">Ver seu perfil</a>
            <a href="#" class="list-group-item">Página de Contato</a>
        </div>
    </div>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-5">
        <!--       <img src="..." alt="..." class="img-rounded">   -->
                Para agilizar a resolução de problemas técnicos foram criados softwares de gerenciamento de chamados.
                <br>
                <br>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5">
          <!--        <img src="..." alt="..." class="img-rounded">   -->
                Este tipo de software tem a função de auxiliar a equipe de suporte para coordenar e solucionar os incidentes que ocorrem com os usuários.
                <br>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-11 col-md-11 col-sm-11">
         <!--        <img src="..." alt="..." class="img-rounded">   -->        
                A proposta do SiGC é a construção de uma aplicação personalizada de gerência de manutenção dos recursos de uma organização, que atenda melhor as necessidades específicas das empresas.
                <br>
                <br>

            </div>

        </div>
    </div>        
</div>


