


<div class="jumbotron">
    <h1>SiGC</h1>
    <p>Sistema de Gerenciamento de Chamados!!!</p>
    <p>
        <br>
        <br>
        <br>
        PAGINA<br>
            * SiGC<br>
            ----------<br>
            FUNÇÃO<br>
            *acesso as paginas do sistema<br>
            ----------<br>
            ATORES<br>
            *tec, ger, user<br>
            ----------<br>
            CONTROLE DE ACESSO OU DETALHES<br>
            *não é necessário colocar um radio buton perguntando o tipo de usuário<br>
            *aqui o usuario ira digitar seu login e senha para acessar
        <br>
       <br>
        <br>
   
       <!-- <a class="btn btn-warning btn-lg" href="<?php echo $this->url('index/logon') ?>" target="_blank">
            
        </a>-->
    </p>
</div>
